"""add nulable

Revision ID: b6e44159d498
Revises: 2864d9276a59
Create Date: 2025-03-05 17:33:23.310119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e44159d498'
down_revision = '2864d9276a59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_items', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_items', 'width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_items', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_items', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_items', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_items', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task_items', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task_items', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_items', 'width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task_items', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
